# ~/.bashrc example for container user

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Load the system-wide bash completion file if it exists
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

# Your prompt, aliases, etc., can go here

